export const
    API_BASE_URL = "http://localhost:3001",
    FETCH_CONTAS_SUCCESS = "FETCH_CONTAS_SUCCESS",
    FETCH_CONTAS_STARTED = "FETCH_CONTAS_STARTED",
    FETCH_CONTAS_FAILED = "FETCH_CONTAS_FAILED"
;