export const
    API_BASE_URL = "http://localhost:3001",
    FETCH_CONTAS_SUCCESS = "FETCH_CONTAS_SUCCESS",
    FETCH_CONTAS_STARTED = "FETCH_CONTAS_STARTED",
    FETCH_CONTAS_FAILED = "FETCH_CONTAS_FAILED",
    FETCH_CATEGORIAS_SUCCESS = "FETCH_CATEGORIAS_SUCCESS",
    FETCH_CATEGORIAS_STARTED = "FETCH_CATEGORIAS_STARTED",
    FETCH_CATEGORIAS_FAILED = "FETCH_CATEGORIAS_FAILED",
    FETCH_MOVIMENTOS_SUCCESS = "FETCH_MOVIMENTOS_SUCCESS",
    FETCH_MOVIMENTOS_STARTED = "FETCH_MOVIMENTOS_STARTED",
    FETCH_MOVIMENTOS_FAILED = "FETCH_MOVIMENTOS_FAILED"
;